//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "VisualDesignPatterns.DesiDiagram")]

namespace VisualDesignPatterns
{
	/// <summary>
	/// DomainClass DesiDiagram
	/// Description for VisualDesignPatterns.DesiDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("VisualDesignPatterns.DesiDiagram.DisplayName", typeof(global::VisualDesignPatterns.DesiDomainModel), "VisualDesignPatterns.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("VisualDesignPatterns.DesiDiagram.Description", typeof(global::VisualDesignPatterns.DesiDomainModel), "VisualDesignPatterns.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::VisualDesignPatterns.DesiDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("efa962b3-491d-4424-811c-fc56462e4837")]
	public partial class DesiDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::VisualDesignPatterns.DesiToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::VisualDesignPatterns.DesignPattern)
			{
				global::VisualDesignPatterns.DesignPatternShape newShape = new global::VisualDesignPatterns.DesignPatternShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::VisualDesignPatterns.AbstractClass)
			{
				global::VisualDesignPatterns.AbstractClassShape newShape = new global::VisualDesignPatterns.AbstractClassShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::VisualDesignPatterns.ConcreteClass)
			{
				global::VisualDesignPatterns.ConcreteClassShape newShape = new global::VisualDesignPatterns.ConcreteClassShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::VisualDesignPatterns.DesignPatternShape.DecoratorsInitialized += DesignPatternShapeDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for DesignPatternShape.
		/// </summary>
		internal static partial class DesignPatternShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for DesignPatternShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::VisualDesignPatterns.DesignPattern.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		#region Constructors, domain class Id
	
		/// <summary>
		/// DesiDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xefa962b3, 0x491d, 0x4424, 0x81, 0x1c, 0xfc, 0x56, 0x46, 0x2e, 0x48, 0x37);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DesiDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DesiDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace VisualDesignPatterns
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::VisualDesignPatterns.ConcreteClass), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::VisualDesignPatterns.AbstractClass), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::VisualDesignPatterns.DesignPattern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is global::VisualDesignPatterns.ConcreteClass)
				{
					parentElement = GetParentForConcreteClass((global::VisualDesignPatterns.ConcreteClass)childElement);
				} else
				if(childElement is global::VisualDesignPatterns.AbstractClass)
				{
					parentElement = GetParentForAbstractClass((global::VisualDesignPatterns.AbstractClass)childElement);
				} else
				if(childElement is global::VisualDesignPatterns.DesignPattern)
				{
					parentElement = GetParentForDesignPattern((global::VisualDesignPatterns.DesignPattern)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::VisualDesignPatterns.Design GetParentForDesignPattern( global::VisualDesignPatterns.DesignPattern root )
			{
				// Segments 0 and 1
				global::VisualDesignPatterns.Design result = root.Design;
				if ( result == null ) return null;
				return result;
			}
			public static global::VisualDesignPatterns.Design GetParentForAbstractClass( global::VisualDesignPatterns.AbstractClass root )
			{
				// Segments 0 and 1
				global::VisualDesignPatterns.DesignPattern root2 = root.DesignPattern;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::VisualDesignPatterns.Design result = root2.Design;
				if ( result == null ) return null;
				return result;
			}
			public static global::VisualDesignPatterns.Design GetParentForConcreteClass( global::VisualDesignPatterns.ConcreteClass root )
			{
				// Segments 0 and 1
				global::VisualDesignPatterns.DesignPattern root2 = root.DesignPattern;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::VisualDesignPatterns.Design result = root2.Design;
				if ( result == null ) return null;
				return result;
			}
		}
		
	
	}
