//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace VisualDesignPatterns
{
	/// <summary>
	/// DomainModel DesiDomainModel
	/// Description for VisualDesignPatterns.Desi
	/// </summary>
	[DslDesign::DisplayNameResource("VisualDesignPatterns.DesiDomainModel.DisplayName", typeof(global::VisualDesignPatterns.DesiDomainModel), "VisualDesignPatterns.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("VisualDesignPatterns.DesiDomainModel.Description", typeof(global::VisualDesignPatterns.DesiDomainModel), "VisualDesignPatterns.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("c118fd14-74b8-4bd3-9c91-53ab17304d6f")]
	public partial class DesiDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DesiDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xc118fd14, 0x74b8, 0x4bd3, 0x9c, 0x91, 0x53, 0xab, 0x17, 0x30, 0x4d, 0x6f);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DesiDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(Design),
				typeof(DesignPattern),
				typeof(AbstractClass),
				typeof(ConcreteClass),
				typeof(DesignHasDesignPatterns),
				typeof(DesignPatternHasAbstractClasses),
				typeof(DesignPatternHasConcreteClasses),
				typeof(DesiDiagram),
				typeof(DesignPatternShape),
				typeof(AbstractClassShape),
				typeof(ConcreteClassShape),
				typeof(global::VisualDesignPatterns.FixUpDiagram),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(DesignPattern), "Name", DesignPattern.NameDomainPropertyId, typeof(DesignPattern.NamePropertyHandler)),
				new DomainMemberInfo(typeof(DesignPattern), "Classification", DesignPattern.ClassificationDomainPropertyId, typeof(DesignPattern.ClassificationPropertyHandler)),
				new DomainMemberInfo(typeof(AbstractClass), "Name", AbstractClass.NameDomainPropertyId, typeof(AbstractClass.NamePropertyHandler)),
				new DomainMemberInfo(typeof(ConcreteClass), "Name", ConcreteClass.NameDomainPropertyId, typeof(ConcreteClass.NamePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(DesignHasDesignPatterns), "Design", DesignHasDesignPatterns.DesignDomainRoleId),
				new DomainRolePlayerInfo(typeof(DesignHasDesignPatterns), "Element", DesignHasDesignPatterns.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(DesignPatternHasAbstractClasses), "DesignPattern", DesignPatternHasAbstractClasses.DesignPatternDomainRoleId),
				new DomainRolePlayerInfo(typeof(DesignPatternHasAbstractClasses), "AbstractClass", DesignPatternHasAbstractClasses.AbstractClassDomainRoleId),
				new DomainRolePlayerInfo(typeof(DesignPatternHasConcreteClasses), "DesignPattern", DesignPatternHasConcreteClasses.DesignPatternDomainRoleId),
				new DomainRolePlayerInfo(typeof(DesignPatternHasConcreteClasses), "ConcreteClass", DesignPatternHasConcreteClasses.ConcreteClassDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(8);
				createElementMap.Add(typeof(Design), 0);
				createElementMap.Add(typeof(DesignPattern), 1);
				createElementMap.Add(typeof(AbstractClass), 2);
				createElementMap.Add(typeof(ConcreteClass), 3);
				createElementMap.Add(typeof(DesiDiagram), 4);
				createElementMap.Add(typeof(DesignPatternShape), 5);
				createElementMap.Add(typeof(AbstractClassShape), 6);
				createElementMap.Add(typeof(ConcreteClassShape), 7);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::VisualDesignPatterns.DesiDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new Design(partition, propertyAssignments);
				case 1: return new DesignPattern(partition, propertyAssignments);
				case 2: return new AbstractClass(partition, propertyAssignments);
				case 3: return new ConcreteClass(partition, propertyAssignments);
				case 4: return new DesiDiagram(partition, propertyAssignments);
				case 5: return new DesignPatternShape(partition, propertyAssignments);
				case 6: return new AbstractClassShape(partition, propertyAssignments);
				case 7: return new ConcreteClassShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(3);
				createElementLinkMap.Add(typeof(DesignHasDesignPatterns), 0);
				createElementLinkMap.Add(typeof(DesignPatternHasAbstractClasses), 1);
				createElementLinkMap.Add(typeof(DesignPatternHasConcreteClasses), 2);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::VisualDesignPatterns.DesiDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new DesignHasDesignPatterns(partition, roleAssignments, propertyAssignments);
				case 1: return new DesignPatternHasAbstractClasses(partition, roleAssignments, propertyAssignments);
				case 2: return new DesignPatternHasConcreteClasses(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "VisualDesignPatterns.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DesiDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DesiDomainModel.resourceManager == null)
				{
					DesiDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DesiDomainModel).Assembly);
				}
				return DesiDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DesiDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DesiDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DesiDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DesiCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DesiDomainModel.copyClosure = copyFilter;
				}
				return DesiDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DesiDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DesiDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DesiDomainModel.removeClosure = removeFilter;
				}
				return DesiDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::VisualDesignPatterns.FixUpDiagram));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::VisualDesignPatterns.FixUpDiagram));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DesiDeleteClosure : DesiDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DesiDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DesiDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DesiDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::VisualDesignPatterns.DesignHasDesignPatterns.ElementDomainRoleId, true);
			DomainRoles.Add(global::VisualDesignPatterns.DesignPatternHasAbstractClasses.AbstractClassDomainRoleId, true);
			DomainRoles.Add(global::VisualDesignPatterns.DesignPatternHasConcreteClasses.ConcreteClassDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DesiCopyClosure : DesiCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DesiCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DesiCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DesiCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace VisualDesignPatterns
{
	/// <summary>
	/// DomainEnumeration: PatternClassification
	/// Description for VisualDesignPatterns.PatternClassification
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum PatternClassification
	{
		/// <summary>
		/// Creational
		/// Description for VisualDesignPatterns.PatternClassification.Creational
		/// </summary>
		[DslDesign::DescriptionResource("VisualDesignPatterns.PatternClassification/Creational.Description", typeof(global::VisualDesignPatterns.DesiDomainModel), "VisualDesignPatterns.GeneratedCode.DomainModelResx")]
		Creational,
		/// <summary>
		/// Structural
		/// Description for VisualDesignPatterns.PatternClassification.Structural
		/// </summary>
		[DslDesign::DescriptionResource("VisualDesignPatterns.PatternClassification/Structural.Description", typeof(global::VisualDesignPatterns.DesiDomainModel), "VisualDesignPatterns.GeneratedCode.DomainModelResx")]
		Structural,
		/// <summary>
		/// Behavioral
		/// Description for VisualDesignPatterns.PatternClassification.Behavioral
		/// </summary>
		[DslDesign::DescriptionResource("VisualDesignPatterns.PatternClassification/Behavioral.Description", typeof(global::VisualDesignPatterns.DesiDomainModel), "VisualDesignPatterns.GeneratedCode.DomainModelResx")]
		Behavioral,
		/// <summary>
		/// Concurrency
		/// Description for VisualDesignPatterns.PatternClassification.Concurrency
		/// </summary>
		[DslDesign::DescriptionResource("VisualDesignPatterns.PatternClassification/Concurrency.Description", typeof(global::VisualDesignPatterns.DesiDomainModel), "VisualDesignPatterns.GeneratedCode.DomainModelResx")]
		Concurrency,
	}
}

