//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualDesignPatterns
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "des";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Visual Design Patterns";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Shirish Goyal";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DesiDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DesiCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DesiExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DesiCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDesiExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DesiCommandSetId), 0x0001);
	
		// Package identifier
		public const string DesiPackageId = "f8a64ea5-4c0f-4711-b312-2e617c9389c4";
		
		// Editor factory identifier
		public const string DesiEditorFactoryId = "0686a5f8-13bc-4013-8312-645769111f2d";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DesiModelExplorerToolWindowId = "054ebb0c-fe10-47c1-92e0-2bc9d7916363";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace VisualDesignPatterns
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DesiCommandSetId = "eb161322-6373-409b-80a8-718260ff2583";
	}
}